name: nextline_todo
description: Aplicación de gestión de tareas con Flutter

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  http: ^0.13.4
  flutter_bloc: ^8.0.1
  validators: ^3.0.0
  expandable: ^5.0.1
  flutter_launcher_icons: 0.9.3
  flutter_native_splash: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter_icons:
  ios: false
  remove_alpha_ios: true
  android: true
  image_path: "assets/images/nextline_logo.png"
  adaptive_icon_background: #0000FF

flutter_native_splash:
  android_12:
    image: "assets/images/nextline_logo.png"
  image: "assets/images/nextline_logo.png"
  color: "#FFFFFF"

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
